update resolvconf service if dnscache is configured

diff --git a/tinydnssec-x/PKGBUILD.in b/tinydnssec-x/PKGBUILD.in
--- a/tinydnssec-x/PKGBUILD.in
+++ b/tinydnssec-x/PKGBUILD.in
@@ -19,7 +19,8 @@ changelog=$pkgname.changes
 _prefix=/usr
 _curvedns_version=0.88
 _mandir=${_prefix}/share/man
-_sysconfdir=/etc/indimail
+_sysconfdir=@sysconfdir@
+_servicedir=@servicedir@
 
 build() {
   cd $srcdir/$pkgname-${pkgver}
@@ -97,23 +98,88 @@ pre_install() {
   done
 }
 
+configure_resolvconf()
+{
+dnscache_configured=0
+if [ -d ${sysconfdir}/dnscache ] ; then
+	dnscache_configured=1
+	if [ -d ${servicedir} ] ; then
+		if [ ! -h ${servicedir}/dnscache ] ; then
+			ln -sf ${sysconfdir}/dnscache ${servicedir}/dnscache || true
+			if [ $? -ne 0 ] ; then
+				dnscache_configured=0
+			fi
+		fi
+	elif [ -h ${servicedir} ] ; then
+		dir=`readlink ${servicedir}`
+		if [ -d $dir ] ; then
+			if [ ! -h $dir/dnscache ] ; then
+				ln -sf ${sysconfdir}/dnscache $dir/dnscache || true
+				if [ $? -ne 0 ] ; then
+					dnscache_configured=0
+				fi
+			fi
+		fi
+	fi
+fi
+if [ $dnscache_configured -eq 1 ] ; then
+  if [ -d ${servicedir}/.svscan ] ; then
+    mkdir -p ${servicedir}/.svscan/variables
+    echo > ${servicedir}/.svscan/variables/UNSHARE # used by svscanboot
+    if [ -x /usr/bin/unshare -a -x ${servicedir}/dnscache/run ] ; then
+      if [ -f ${servicedir}/.svscan/run ] ; then
+        /bin/chmod +x ${servicedir}/.svscan/run
+      fi
+    fi
+  fi
+  grep resolvconf ${servicedir}/.svscan/variables/.options > /dev/null 2>&1
+  if [ $? -ne 0 ] ; then
+    options="`cat ${servicedir}/.svscan/variables/.options`"
+    options="$options --resolvconf"
+    mv ${servicedir}/.svscan/variables/.options \
+      ${servicedir}/.svscan/variables/.options.noresolvconf
+    echo $options > ${servicedir}/.svscan/variables/.options
+    if [ -d ${servicedir}/resolvconf/variables ] ; then
+     echo $options > ${servicedir}/resolvconf/variables/.options
+    fi
+    if [ -x ${prefix}/sbin/minisvc ] ; then
+      ${prefix}/sbin/minisvc --refreshsvc=/service/.svscan
+    fi
+  fi
+fi
+}
+
 post_install() {
+  dnscache_configured=0
   if [ ! -d ${_sysconfdir}/dnscache ] ; then
     ${_prefix}/sbin/dnscache-conf Gdnscache qmaill ${_sysconfdir}/dnscache 127.0.0.1
     if [ $? -eq 0 ] ; then
-      if [ ! -h /service/dnscache ] ; then
-        ln -s ${_sysconfdir}/dnscache /service/dnscache
+      dnscache_configured=1
+      if [ -d ${servicedir} ] ; then
+        if [ ! -h /service/dnscache ] ; then
+          ln -s ${_sysconfdir}/dnscache /service/dnscache
+          if [ $? -ne 0 ] ; then
+            dnscache_configured=0
+          fi
+        fi
+      elif [ -h ${servicedir} ] ; then
+        dir=`readlink ${servicedir}`
+        if [ -d $dir ] ; then
+          if [ ! -h ${servicedir}/dnscache ] ; then
+            ln -sf ${sysconfdir}/dnscache ${servicedir}/dnscache || true
+            if [ $? -ne 0 ] ; then
+              dnscache_configured=0
+            fi
+          fi
+        fi
       fi
+	else
+      echo "${prefix}/sbin/dnscache-conf Gdnscache qmaill ${sysconfdir}/dnscache 127.0.0.1: failed"
     fi
   else
+    dnscache_configured=1
     if [ ! -h /service/dnscache ] ; then
       ln -s ${_sysconfdir}/dnscache /service/dnscache
-    fi
-  fi
-  echo > /service/.svscan/variables/UNSHARE
-  if [ -x /usr/bin/unshare -a -x /service/dnscache/run ] ; then
-    if [ -f /service/.svscan/run ] ; then
-      /bin/chmod +x /service/.svscan/run
     fi
   fi
   for i in tinydns dqcache curvedns
@@ -146,6 +212,7 @@ post_install() {
 }
 
 post_upgrade() {
+  configure_resolvconf
   if [ -f ${_prefix}/bin/svok ] ; then
     for i in tinydns tinydns/log dnscache dnscache/log curvedns curvedns/log dqcache dqcache/log
     do
