added command line option to turn on verbose rpmbuild

diff --git a/tinydnssec-1.05/create_rpm b/tinydnssec-1.05/create_rpm
--- a/tinydnssec-1.05/create_rpm
+++ b/tinydnssec-1.05/create_rpm
@@ -1,4 +1,33 @@
 #!/bin/sh
+version=$(cat conf-version)
+
+if [ -f /etc/debian_version ] ; then
+	echo "you can't do rpmbuild on an insane system" 1>&2
+	exit 1
+fi
+
+verbose=0
+while test $# -gt 0; do
+    case "$1" in
+    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
+	;;
+    *) optarg=
+	;;
+    esac
+
+    case "$1" in
+    --verbose)
+	verbose=1
+    ;;
+    *)
+    echo "invalid option [$1]"
+    read key
+    usage 1
+    ;;
+    esac
+
+    shift
+done
 if test -f $HOME/.rpmmacros
 then
 	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
@@ -11,7 +40,7 @@ then
 else
 	rpmbuild=$HOME/rpmbuild
 fi
-version=$(cat conf-version)
+
 cd ..
 if [ -d stage ] ; then
 	/bin/rm -rf stage
@@ -73,22 +102,32 @@ if [ " $key" = " Y" -o " $key" = " y" ] ; then
 		cd debian
 		make
 	fi
-	rpmbuild -ba --clean /tmp/tinydnssec.spec
-	/bin/rm -f /tmp/tinydnssec.spec
-	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
-	rpm --addsign $rpmbuild/RPMS/$build_arch/tinydnssec-"$version"-"1.$release".$dist.$build_arch.rpm
-	rpm --addsign $rpmbuild/SRPMS/tinydnssec-"$version"-"1.$release".$dist.src.rpm
-	echo -n "RPM lint for tinydnssec-"$version"-1."$release" (Y/N) - "
-	read key
-	if [ " $key" = " Y" -o " $key" = " y" ] ; then
-		(
-		echo tinydnssec-"$version"-"1.$release".$dist.$build_arch
-		rpmlint $rpmbuild/RPMS/$build_arch/tinydnssec-"$version"-"1.$release".$dist.$build_arch.rpm
-		echo ------------------------
-		echo tinydnssec-"$version"-"1.$release".$dist.src.rpm
-		rpmlint $rpmbuild/SRPMS/tinydnssec-"$version"-"1.$release".$dist.src.rpm
-		echo ------------------------
-		) 2>&1 | less
+	if [ $verbose -eq 0 ] ; then
+		echo "rpmbuild -ba --clean --quiet /tmp/tinydnssec.spec"
+		rpmbuild -ba --clean --quiet /tmp/tinydnssec.spec
+	else
+		echo "rpmbuild -ba --clean /tmp/tinydnssec.spec"
+		rpmbuild -ba --clean /tmp/tinydnssec.spec
+	fi
+	if [ $? -eq 0 ] ; then
+		/bin/rm -f /tmp/tinydnssec.spec
+		build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
+		rpm --addsign $rpmbuild/RPMS/$build_arch/tinydnssec-"$version"-"1.$release".$dist.$build_arch.rpm
+		rpm --addsign $rpmbuild/SRPMS/tinydnssec-"$version"-"1.$release".$dist.src.rpm
+		echo -n "RPM lint for tinydnssec-"$version"-1."$release" (Y/N) - "
+		read key
+		if [ " $key" = " Y" -o " $key" = " y" ] ; then
+			(
+			echo tinydnssec-"$version"-"1.$release".$dist.$build_arch
+			rpmlint $rpmbuild/RPMS/$build_arch/tinydnssec-"$version"-"1.$release".$dist.$build_arch.rpm
+			echo ------------------------
+			echo tinydnssec-"$version"-"1.$release".$dist.src.rpm
+			rpmlint $rpmbuild/SRPMS/tinydnssec-"$version"-"1.$release".$dist.src.rpm
+			echo ------------------------
+			) 2>&1 | less
+		fi
+	else
+		/bin/rm -f /tmp/tinydnssec.spec
 	fi
 else
 	/bin/rm -rf stage
